# Generated by Django 5.1.2 on 2024-10-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_photo',
            new_name='personal_photo',
        ),
    ]
